### ISSUE TITLE
need to escape things that would link to issues

### ISSUE THREAD

**Issue by dbaron** [dbaron/wgmeeting-github-ircbot#11]
@zcorpan [pointed out](https://log.csswg.org/irc.w3.org/css/2017-06-21/#e824956) that the bot produces things like #1 in comments that need to be escaped somehow to prevent them from being considered links to github issues.  From the look of https://github.com/w3c/csswg-drafts/pull/1 this is a persistent problem.  But it appears that his suggested solution of "\\#1" doesn't work.

**Comment by zcorpan** [comment]
Insert U+200B in between?

**Comment by dbaron** [comment]
I wonder if U+FEFF is more appropriate, though.  It is called "zero width no-break space"; "byte order mark" is just its alternative name.
