### ISSUE TITLE
Don't claim that it's always the CSS WG

### ISSUE THREAD

**Issue by nigelmegitt** [dbaron/wgmeeting-github-ircbot#14]
Properly, the group name should be configurable and associated with the IRC channel, but in the first instance, at least just say "The Working Group" rather than "The CSS Working Group".

**Comment by dbaron** [comment]
Reopening to actually associate WG names with IRC channels.

**Comment by astearns** [comment]
Getting the working group name from the IRC channel will help with comments like this one:

https://github.com/w3c/csswg-drafts/issues/2118#issuecomment-376280480

Where the SVG working group added a comment to a CSS working group issue.

**Comment by nigelmegitt** [comment]
@astearns I agree, and note that there's a mapping from IRC channel name to WG name, i.e. they're not the same string. I'm sure that's available as data _somewhere_, because for example trackbot on IRC knows it.

**Comment by dbaron** [comment]
I think the data would go in the bot's JSON configuration.

That said, I'm in the middle of a large refactoring for other reasons, and I don't want to touch this until after that.
