### ISSUE TITLE
Allow SUMMARY as well as RESOLUTION and RESOLVED

### ISSUE THREAD

**Issue by nigelmegitt** [dbaron/wgmeeting-github-ircbot#15]
The keywords `RESOLVED` and `RESOLUTION` at the beginning of a line are picked up by scribe.perl and used to describe a resolution. Sometimes the result of a discussion just needs to be summarised, so a keyword not used by scribe.perl such as `SUMMARY`.

**Comment by dbaron** [comment]
I merged the PR, although I'm a little concerned that the bot will still describe the result as a resolution.

**Comment by nigelmegitt** [comment]
Ah, thanks for that - I should have realised. Will take a look at proposing something to change that behaviour.

**Comment by nigelmegitt** [comment]
Actually it turns out that it doesn't describe the result as a resolution. See https://github.com/w3c/ttml2/issues/271#issuecomment-326332175 for an example. 

There's no further action to take I think? If you agree @dbaron I think this can be closed.

**Comment by dbaron** [comment]
Right before the list that comment does say "agreed to the following resolutions", which isn't quite right.

One other thing I'd like to clean up is that it shouldn't remove `Agenda+` or `Agenda+ F2F` tags if there's only a SUMMARY and not a RESOLUTION.
