### ISSUE TITLE
bot should comment on pull requests in addition to issues

### ISSUE THREAD

**Issue by dbaron** [dbaron/wgmeeting-github-ircbot#19]
@zcorpan pointed out on IRC after today's CSS WG teleconference that the bot failed to comment on w3c/csswg-drafts#1805.  I believe this is because it's a pull request rather than an issue.

We presumably both:
* need to fix the parsing of issues URLs to check for pull requests as well
* need to make sure the github apis being used work for commenting on pull requests, or adjust the calls if not

**Comment by AmeliaBR** [comment]
Were you able to look into this, to see how much work is required?

If it's just a matter of changing the Regex in https://github.com/dbaron/wgmeeting-github-ircbot/blob/8f1a5312a5d0f23f75461ba0e45ea4f923276be3/src/lib.rs#L690-L695, then it would be great to get this fix sooner than not.

**Comment by dbaron** [comment]
Given that `issue` is the name of one of the functions, I strongly suspect that https://github.com/dbaron/wgmeeting-github-ircbot/blob/8f1a5312a5d0f23f75461ba0e45ea4f923276be3/src/lib.rs#L809-L814 also needs to be adjusted.

**Comment by AmeliaBR** [comment]
Promising, [from the Github API](https://developer.github.com/v3/pulls/):

> Comments on pull requests can be managed via the Issue Comments API.

The [Hubcaps library documentation](http://lessis.me/hubcaps/hubcaps/repositories/struct.Repository.html#method.issue) is a little stingy, though. Are you able to spin up a quick demo environment, and run a test of whether `repo.issue(number_for_a_pr)` gives a valid object back? There doesn't seem to be any equivalent "get a single PR by its number" method.

**Comment by dbaron** [comment]
hubcaps (the current version at least, though I'm behind; see #24) looks like it has the needed API in `repo.pulls().get(number).comments().  I'd need to double-check that's in the version I'm currently tied to.

**Comment by AmeliaBR** [comment]
Excellent! And thanks again for this whole tool.
