### ISSUE TITLE
Consider using toml for config file?

### ISSUE THREAD

**Issue by upsuper** [dbaron/wgmeeting-github-ircbot#33]
I think there is a general consensus that JSON isn't a good format for configuration because its rather strict grammar requirement (no comment allowed, no trailing comma allowed, etc.)

The Rust ecosystem seems to lean towards using toml to serve as config. It has a grammar more friendly to human editing.

**Comment by dbaron** [comment]
I think that's probably fine, although I'm a little worried about folks in the W3C community being less familiar with it, since I'd want them to be able to change it easily.  What does the heavily-nested stuff like what I just added for #14 look like in TOML?

**Comment by upsuper** [comment]
With the current form, it would probably need to be
```toml
[bot.channel."#css"]
group = "CSS Working Group"
github_repos_allowed = [
    "w3c/csswg-drafts",
    "w3c/fxtf-drafts",
    "w3c/css-houdini-drafts",
    "w3c/svgwg",
    "web-platform-tests/wpt",
    "WICG/animation-worklet",
]

[bot.channel."#svg"]
# ...
```

But if we can move channel outside from bot section, it would probably look better (fewer level in the section title).

**Comment by dbaron** [comment]
Moving the channels to outside the bot section would mean more objects to pass around throughout the code, though, right?
