### ISSUE TITLE
Generate a topic with the name of the issue

### ISSUE THREAD

**Issue by nigelmegitt** [dbaron/wgmeeting-github-ircbot#45]
We'd love to be able to do something like:

```
github-bot, new topic [url to github issue]
```

and have the bot do:

1. Close the current topic and post as normal
2. Look up the name of the referenced issue
3. Insert into the IRC channel "Topic: [name]"
4. Start recording for that issue.

This would save us having to do painful copy/pastes of the title and URL for each issue.

**Comment by dbaron** [comment]
Yeah, this seems like a good idea.  Given that the bot responds to commands both directly or with `/me` I think the thing to do when this command is issued is to:
* end the previous topic
* get the github issue
* issue a line `Topic: [title of github issue][user/repo #number]`
* issue a line `github: [url of github issue]`

I also think "take up" might be a reasonable synonym for the command.

Not sure when I'd have time to do this, though...

**Comment by nigelmegitt** [comment]
Thank you!
