### ISSUE TITLE
`subtopic:`

### ISSUE THREAD

**Issue by fantasai** [dbaron/wgmeeting-github-ircbot#59]
Was just using the `subtopic:` command while minuting for the Process CG, and noticed that githubbot does not close out topics when it is used. I don't know if this was a conscious decision or if it just doesn't support `subtopic:` but it basically meant we couldn't use the bot for the entire discussion because it mashed all the related issues together.

**Comment by dbaron** [comment]
I'd never heard of "subtopic:" being used.  What other tools support it?

**Comment by fantasai** [comment]
scribe.perl v2 https://w3c.github.io/scribe2/scribedoc.html#notes

**Comment by nigelmegitt** [comment]
Seems like a good idea to me - @fantasai how did you expect this to work with github-bot? I'd envisage something like:

```
Topic: SomeParticularSpec Issues
Subtopic: SomeIssue w3c/SomeParticularSpec#123
github: https://github.com/w3c/SomeParticularSpec/issues/123
[github-bot responds to say that it will post everything on this subtopic to the issue]
[discussion]
Subtopic: SomeOtherIssue ...
[github-bot notifies that it will post above discussion against #123]
```

whereas the existing behaviour would still need to work, in the absence of (or before) a subtopic:

```
Topic: SomeOtherSpecIssue w3c/SomeOtherSpec#456
github: https://github.com/w3c/SomeOtherSpec/issues/456
[github-bot responds to say that it will post everything on this topic to the issue]
[discussion]
[Topic|Subtopic]: Next topic/subtopic
[github-bot notifies that it will post above discussion against #456]
```

Just thought it worth checking in case the request here is instead to do something different e.g. what if the group wants to discuss subtopics within a single issue and have github-bot format the posted issues to pull out each subtopic distinctly rather than one single `<details>` element?

```
Topic: SomeOtherSpecIssue w3c/SomeOtherSpec#456
github: https://github.com/w3c/SomeOtherSpec/issues/456
[github-bot responds to say that it will post everything on this topic to the issue]
[discussion]
Subtopic: Key goals for this issue
[discussion]
Subtopic: Next steps
[discussion]
Topic: Next topic
[github-bot notifies that it will post above discussion against #456 and does so with each subtopic pulled out clearly]
```

**Comment by fantasai** [comment]
@nigelmegitt Interesting point. Maybe in that case subtopic should terminate an issue if it started in a subtopic issue, but not terminate it if it's at the higher level?

Fwiw, mostly we've been using subtopic to break a larger theme into issue-per-subtopic discussions, so definitely an issue tagged in a subtopic should be terminated by the next subtopic.

I think it's also OK if both topic and subtopic terminate the issue. You can always repaste the URL into each subtopic, and it might actually be nice if github-bot posts separate comments for each subtopic, given that it doesn't actually format the minutes.
