### ISSUE TITLE
Extract ACTION lines

### ISSUE THREAD

**Issue by fantasai** [dbaron/wgmeeting-github-ircbot#71]
It's often useful to pull out ACTION lines so they don't get lost, even when they're not resolutions. Maybe handling them similar to SUMMARY would work?

**Comment by nigelmegitt** [comment]
I've often wondered if the bot should have the ability to respond to ACTION lines by creating linked issues in the same repo.

**Comment by fantasai** [comment]
@nigelmegitt  I think that would be a separate feature request, with a lot of different implications than just highlighting a line in the logs. :)

**Comment by fantasai** [comment]
I think the pattern to extract would be something like `ACTION(\s+[\w\s]+)?: .*` to capture both `ACTION: someone to do something` and `ACTION someone: do something`  which both seem to be reasonably common patterns I've encountered

**Comment by nigelmegitt** [comment]
> @nigelmegitt I think that would be a separate feature request, with a lot of different implications than just highlighting a line in the logs. :)

raised as #75
