### ISSUE TITLE
Alias “take up”

### ISSUE THREAD

**Issue by fantasai** [dbaron/wgmeeting-github-ircbot#72]
Wanted to suggest a few minor syntax features

- aliasing  “take up” to “topic”
- also allowing “subtopic” and having that spit out “Subtopic: ” instead of “Topic: ”
- ignoring any excess punctuation such as commas or colons when pattern matching these commands :)

**Comment by dbaron** [comment]
`take up subtopic` is already supported.  (Ask `github-bot` for `help`.)

The place where punctuation is needed is when addressing github-bot.  I'm a little hesitant to remove that check; it would mean that any discussion *about* github-bot would give errors about parsing of commands.

**Comment by fantasai** [comment]
> take up subtopic is already supported. (Ask github-bot for help.)

Ah, very nice.

My suggestion was to also have

`/me github-bot topic XXX` and `/me github-bot subtopic XXX` work; this is faster to type than `/me github-bot, take up [subtopic] XXX` and seems sufficiently unambiguous

> The place where punctuation is needed is when addressing github-bot. I'm a little hesitant to remove that check; it would mean that any discussion about github-bot would give errors about parsing of commands.

Hm, I see. How about if it matches the command syntax and is valid, it's parsed as a valid command even if punctuation is missing; if it is not valid, don't say anything and ignore it.

**Comment by dbaron** [comment]
> /me github-bot topic XXX and /me github-bot subtopic XXX work; this is faster to type than /me github-bot, take up [subtopic] XXX and seems sufficiently unambiguous

Yeah, that's probably true.  I guess I should do that.  Perhaps "take up" was a mistake...

> Hm, I see. How about if it matches the command syntax and is valid, it's parsed as a valid command even if punctuation is missing; if it is not valid, don't say anything and ignore it.

I think this sort of handling is also undesirable, since if someone gets in the habit of using the bot that way, they'll never see error messages and might not even know it can report errors when used differently.

**Comment by dbaron** [comment]
There's also @nigelmegitt 's original suggestion of "new topic" from #45.  Not sure if that's better or worse than just "topic".  It might be better since "topic" might be confusable with the old (prior to #45) way of using the bot.

**Comment by fantasai** [comment]
As a scribe, I really want to optimize for how fast can I type it. :) It's hard enough just to keep up with the conversation.
