### ISSUE TITLE
github-bot shouldn't listen to /me lines

### ISSUE THREAD

**Issue by tabatkins** [dbaron/wgmeeting-github-ircbot#76]
Currently, if you send a `/me github-bot ....` line in IRC, for example to show someone the syntax of a command, github-bot will still take action on it. It responds with a /me as well, so it's certainly noticing the form.

It's possible that github-bot wouldn't actually perform the action, but in my case I'd said `/me github-bot, take up <url here>` so it responded that it couldn't find a URL.

**Comment by dbaron** [comment]
This was an intentional feature, so that people could issue unlogged commands to github-bot, which I think is often preferred since the commands don't need to be minuted.  I think this would be a somewhat major change...

**Comment by tabatkins** [comment]
oh huh, i guess that makes sense
